#!/bin/bash
# @software: PyCharm
# @author: Lionel Johnson
# @contact: https://fairy.host
# @organization: https://github.com/FairylandFuture
# @since: 2024-06-22 18:07:39 UTC+8

# Terminal output color
RESET_COLOR="\e[0m"
RED_COLOR="\e[31m"
GREEN_COLOR="\e[32m"

CONTAINER_NAME="picsur-service"
CONTAINER_USER="$(id -u)"
CONTAINER_GROUP="$(id -g)"

check_requirements() {
  if ! command -v docker &>/dev/null; then
    echo -e "${RED_COLOR}Docker is not installed. Please install Docker and try again.${RESET_COLOR}"
    exit 1
  fi
}

main() {
  check_requirements

  if [ "$EUID" -ne 0 ]; then
    echo -e "${RED_COLOR}The script must be run as root or with sudo.${RESET_COLOR}"
    exit
  fi

  if [ "$SUDO_USER" = "root" ] || [ "$USER" == "root" ]; then
    echo -e "${RED_COLOR}Running as root, creating docker-run user and group...${RESET_COLOR}"
    useradd -M -N -s /sbin/nologin -g docker docker-executor >>/dev/null
    usermod -aG docker docker-executor
    CONTAINER_USER=$(id -u docker-executor)
    CONTAINER_GROUP=$(id -g docker-executor)
  else
    CONTAINER_USER=$(id -u "$SUDO_USER")
    CONTAINER_GROUP=$(id -g "$SUDO_USER")
  fi

  local docker_command=(
    "docker"
    "run"
    "-d"
    "--name" "$CONTAINER_NAME"
    "--network" "DockerCustomNet"
    "--ip" "173.1.10.4"
    "--user" "$CONTAINER_USER":"$CONTAINER_GROUP"
    "--privileged=true"
    "-e" "TZ=Asia/Shanghai"
    "-e" "PICSUR_HOME=0.0.0.0"
    "-e" "PICSUR_PORT=8080"
    "-e" "PICSUR_DB_HOST=173.1.10.2"
    "-e" "PICSUR_DB_PORT=5432"
    "-e" "PICSUR_DB_USER=picsur"
    "-e" "PICSUR_DB_PASSWORD=picsur"
    "-e" "PICSUR_DB_DATABASE=picsur"
    "-p" "51004:8080"
    "--restart" "always"
    "ghcr.io/caramelfur/picsur:latest"
  )

  if "${docker_command[@]}"; then
    echo -e "${GREEN_COLOR}PostgreSQL service started successfully.${RESET_COLOR}"
  else
    echo -e "${RED_COLOR}Failed to start PostgreSQL service.${RESET_COLOR}"
  fi

  docker logs -f "$CONTAINER_NAME"

}

main
