# gradle.properties
# \u52A0\u5927Gradle\u8FD0\u884C\u5185\u5B58
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC -Dfile.encoding=UTF-8
# \u5F00\u542F\u914D\u7F6E\u7F13\u5B58\uFF08\u7B2C\u4E8C\u6B21\u540C\u6B65\u901F\u5EA6\u63D0\u534780%+\uFF09
org.gradle.configuration-cache=true
# \u5F00\u542F\u6784\u5EFA\u7F13\u5B58
org.gradle.caching=true
# \u5F00\u542F\u5E76\u884C\u6784\u5EFA
org.gradle.parallel=true
# \u5F00\u542F\u957F\u671F\u5B58\u6D3B\u7684\u5B88\u62A4\u8FDB\u7A0B
org.gradle.daemon=true
# \u7981\u7528\u52A8\u6001\u7248\u672C\u68C0\u67E5\uFF0C\u907F\u514D\u6BCF\u6B21\u540C\u6B65\u62C9\u53D6\u8FDC\u7A0B\u7248\u672C
org.gradle.dependency.verification=strict
org.gradle.configuration-cache.parallel=true
