spring.application.name=spring-demo
server.address=0.0.0.0
spring.profiles.active=dev
# MySQL
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
# MyBatis
#mybatis.configuration.map-underscore-to-camel-case=true

