# @software: PyCharm
# @author: Beau Dean
# @contact: https://fairy.host
# @organization: https://github.com/FairylandFuture
# @datetime: 2026-05-02 23:53:51 UTC+08:00
---

database:
  postgresql:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: postgres
splitter:
  chunk_size: 100
  chunk_overlap: 20
  max_length: 512
