/*****************************************************
 * @software: IntelliJ IDEA
 * @author: Lionel Johnson
 * @contact: https://fairy.host
 * @organization: https://github.com/FairylandFuture
 * @datetime: 2026-04-21 00:42:36 UTC+08:00
 ****************************************************/
syntax = "proto3";

option java_multiple_files = false;
option java_package = "host.fairy.grpc";
option java_outer_classname = "TestProto";

message TestRequest {
  string requestMessage = 1;
}

message TestResponse {
  string responseMessage = 1;
}

service TestService {
  rpc testMethod (TestRequest) returns (TestResponse) {};
}
