#!/bin/bash
# @File: restart-auto-git-commit-service
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-17

podman restart auto-git-commit
