#!/bin/bash
# @File: start-joplin-service
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-19

docker run -d --name joplin-service \
  -e TZ=Asia/Shanghai \
  -e APP_PORT=22300 \
  -e APP_BASE_URL=https://joplin.cloud.fairies.ltd \
  -e DB_CLIENT=pg \
  -e POSTGRES_HOST=mapping.fairies.ltd \
  -e POSTGRES_USER=austinservice \
  -e POSTGRES_PASSWORD=Austin.pwd:112#. \
  -e POSTGRES_PORT=51005 \
  -e POSTGRES_DATABASE=internal_container_joplin \
  -p 51020:22300 \
  joplin/server:latest
