#!/bin/bash
# @File: start-affine-service
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-19

docker run -d --name affine-service \
  -e TZ=Asia/Shanghai \
  -p 51020:3000 \
  -v /home/ace/data/docker/volume/affine/data:/app/data \
  --restart always \
  ghcr.io/toeverything/affine-self-hosted:latest
