#!/bin/bash
# @File: start-portainer-agent-service
# @Editor: PyCharm
# @Author: Lionel Johnson
# @HomePage: https://fairy.host
# @CreatedTime: 2024-03-01

docker run -d --name portainer-agent-service \
  --notwork DockerCustomNet \
  --ip 173.1.254 \
  -e TZ=Asia/Shanghai \
  -p 52999:9001 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v /var/lib/docker/volumes:/var/lib/docker/volumes \
  --restart=always \
  portainer/agent:latest
