#!/bin/bash
# File: start-siyuan-service
# Editor: PyCharm
# Author: Austin (From Chengdu.China) https://fairy.host
# HomePage: https://github.com/AustinFairyland
# OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# CreatedTime: 12/23/2023

docker run -d --name siyuan-service \
  --network DockerCustomNet \
  --ip 173.1.11.5 \
  -e TZ=Asia/Shanghai \
  -p 51005:6806 \
  -v /home/austin/data/containers/volume/siyuan-service/Austin:/siyuan/Austin \
  --restart always \
  b3log/siyuan:latest --workspace=/siyuan/Austin/ \
  --accessAuthCode="Austin.pwd:112#."
