#!/bin/bash
# @File: docker-create-network
# @Editor: PyCharm
# @Author: Austin (From Chengdu.China) https://fairy.host
# @HomePage: https://github.com/AustinFairyland
# @OperatingSystem: Windows 11 Professional Workstation 23H2 Canary Channel
# @CreatedTime: 2024-01-20

# 创建桥接设备
# sudo ip link add name DockerCustomNet type bridge
# 启用桥接设备
# sudo ip link set DockerCustomNet up
# 确认桥接设备创建成功
# sudo ip link show DockerCustomNet

docker network create DockerCustomNet \
  --driver bridge \
  --ipam-driver default \
  --subnet 173.1.0.0/16 \
  --gateway 173.1.0.1 \
  --ip-range 173.1.0.0/24 \
  --opt com.docker.network.bridge.default_bridge=true \
  --opt com.docker.network.bridge.enable_icc=true \
  --opt com.docker.network.bridge.enable_ip_masquerade=true \
  --opt com.docker.network.bridge.host_binding_ipv4=0.0.0.0 \
  --opt com.docker.network.bridge.name=DockerCustomNet \
  --opt com.docker.network.driver.mtu=1500 \
  --label internal.network.name=DockerCustomNet
