# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Welcome.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Welcome.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rWelcome.proto\"\x1e\n\x0eWelcomeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x0fWelcomeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\x0eWelcomeService\x12.\n\x07welcome\x12\x0f.WelcomeRequest\x1a\x10.WelcomeResponse\"\x00\x42)\n\x17host.fairy.grpc.welcomeB\x0cWelcomeProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Welcome_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027host.fairy.grpc.welcomeB\014WelcomeProtoP\000'
  _globals['_WELCOMEREQUEST']._serialized_start=17
  _globals['_WELCOMEREQUEST']._serialized_end=47
  _globals['_WELCOMERESPONSE']._serialized_start=49
  _globals['_WELCOMERESPONSE']._serialized_end=83
  _globals['_WELCOMESERVICE']._serialized_start=85
  _globals['_WELCOMESERVICE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
